### ISSUE TITLE
Your browser is no longer supported

### ISSUE THREAD

**Issue by oupala** [Alkarex/EasyRSS#75]
EasyRSS contains an embedded browser used to display articles when viewed in an "original view".

This embedded browser seems to be very old as some websites display a message saying that "Your browser is no longer supported":

![Screenshot_20220525-202126](https://user-images.githubusercontent.com/13458743/206192445-02e671f4-4044-4654-a13f-3582de4298ab.png)

How old is this embedded browser?

Do you think it could be possible to upgrade it?

**Comment by Frenzie** [comment]
The embedded browser isn't part of EasyRSS, but part of Android.

See https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US&pli=1 for how that's normally kept up to date, but I'm guessing you may have a custom ROM.

**Comment by oupala** [comment]
Oh, thanks for this information @Frenzie! I wouldn't have guessed that it was depending on Android version.

But you're totally right: I'm using a custom rom. What is the impact of using a custom rom?

**Comment by Frenzie** [comment]
Nothing much other than what you're looking at. If up to date it should be very similar to any other up to date Android, if no longer updated much the same. Most of the difference lies in the Google set of apps that are used instead of the hardly developed since version 4 or so base Android ones for texting, calculator, calendar, etc. and many people use alternatives anyway. (Also I think LineageOS for example has their own updated forks.) Webview is fairly unique in that it running an older version might actually be noticeable in daily life as you've seen.

You might be able to update the Webview component. [Here](https://forum.xda-developers.com/t/best-way-to-update-webview-on-custom-rom.4479333/)'s a quick search result.

On my phone you can select which browser you want to use for Webview in developer options btw, but none of the other browsers I've installed are available as an option, so I'm not sure how that works.

But it's probably a lot simpler to just open the site in a browser. ;-)

**Comment by oupala** [comment]
Thanks a lot for this extensive answer.

It might be time to close this issue then...
